languageCode = "en-us"
title = "Scalatra"
# baseurl = "/"
# baseurl = "http://example.org/"

[params]
  highlightStyle = "github"

[[menu.main]]
  name   = "Getting started"
  url    = "/getting-started/"
  weight = 10

[[menu.main]]
  name   = "Guides"
  url    = "/guides/"
  weight = 20

[[menu.main]]
  name   = "News"
  url    = "/news/"
  weight = 30

[[menu.main]]
  name   = "Community"
  url    = "/community/"
  weight = 40

[[menu.main]]
  name   = "Community"
  url    = "/community/"
  weight = 40
